config/routes.rb
Bloccit::Application.routes.draw do

  # custom registration controller for image upload bug
  devise_for :users, :controllers => { :registrations => "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  # resources :posts, :path => 'articles'

  #user profiles
  resources :users, only: [:show, :index]

  resources :posts, only: [:index]

  resources :topics do
      resources :posts, except: [:index], controller: 'topics/posts', :path => 'articles' do
          resources :comments, only: [:create, :destroy]
          get '/up-vote', to: 'votes#up_vote', as: :up_vote
          get '/down-vote', to: 'votes#down_vote', as: :down_vote
          resources :favorites, only: [:create, :destroy]
      end
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy

    scope :visible_to, lambda { |user| user ? scoped : where(public: true) }
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  def index
      @posts = Post.all
  end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:id])
    @comments = @post.comments.reverse_order
    @comment = Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])
      authorize @post
  end

  def update
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])
      authorize @post
      if @post.update_attributes(post_params)
          flash[:notice] = "Post was updated"
          redirect_to @topic
      else
          flash[:error] = "There was an error saving the post.  Please try again."
          render :edit
      end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save
        flash[:notice] = "Post was saved."
        redirect_to @topic
    else
        flash[:error] = "There was an error saving the post.  Please try again"
        render :new
    end
  end

  def destroy
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])

      title = @post.title
      authorize @post
      
      if @post.destroy
          flash[:notice] = "\"#{title}\" was deleted successfully."
          redirect_to @topic
      else
          flash[:error] = "There was an error deleting the post."
          render :show
      end
  end

  private

  def post_params
      params.require(:post).permit(:title, :body, :post_image)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
      @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
  end

  def new
      @topic = Topic.new
      authorize @topic
  end

  def edit
      @topic = Topic.find(params[:id])
      authorize @topic
  end

  def show
      @topic = Topic.find(params[:id])
      authorize @topic
      @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def create
      @topic = Topic.new(topic_params)
      authorize @topic
      if @topic.save
          flash[:notice] = "Topic was saved successfully."
          redirect_to @topic
      else
          flash[:error] = "Error creating topic.  Please try again."
          render :new
      end
  end

  def update
      @topic = Topic.find(params[:id])
      authorize @topic
      if @topic.update_attributes(topic_params)
          redirect_to @topic
      else
          flash[:error] = "Error saving topic.  Please try again"
          render :edit
      end
  end

  def destroy
      @topic = Topic.find(params[:id])
      name = @topic.name
      authorize @topic
      if @topic.destroy
          flash[:notice] = "\"#{name}\" was deleted successfully."
          redirect_to topics_path
      else
          flash[:error] = "There was an error deleting the topic."
          render :show
      end
  end

  private

  def topic_params
      params.require(:topic).permit(:name, :description, :public)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topics</h1>

<div class="row">
    <div class="span-6">
        <p>Guidelines for new topic:</p>
        <ul>
            <li>Make sure content is appropriate.</li>
            <li>Make sure content is appropriate.</li>
            <li>Make sure content is appropriate.</li>
            <li>Make sure content is appropriate.</li>
        </ul>
    </div>

    <div class="span-6">
        <%= form_for @topic, html: { class: 'form-horizontal' } do |f| %>
            <div class="control-group">
                <%= f.label :name, class: 'control-label' %>
                <div class="controls">
                    <%= f.text_field :name %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label :description, class: 'control-group' %>
                <div class="controls">
                    <%= f.text_area :description, rows: 8 %>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <%= f.label :public, class: 'checkbox' do %>
                        <%= f.check_box :public %> Public topic
                    <% end %>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <%= f.submit "Save", class: 'btn' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/topics/index.html.erb
<% if policy(Topic.new).show? %>
<h1>Topics</h1>

<div class="row">

    <div class="span8">
        <% @topics.each do |topic| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to topic.name, topic %>
                    </h4>
                    <small>
                        <%= topic.description %>
                    </small>
                </div>
            </div>
        <% end %>
        <%= will_paginate @topics %>
    </div>

    <div class="span4">
        <% if policy(Topic.new).create? %>
            <%= link_to "New Topic", new_topic_path, class: 'btn btn-large btn-block' %>
        <% end %>
    </div>

</div>

<% end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
    <div class="span-6">
        <p>Guidelines for new topics:</p>
        <ul>
            <li>Make sure conent is appropriate.</li>
            <li>Make sure conent is appropriate.</li>
            <li>Make sure conent is appropriate.</li>
            <li>Make sure conent is appropriate.</li>
        </ul>
    </div>

    <div class="span-6">
        <%= form_for @topic, html: { class: 'form-horizontal' } do |f| %>
            <div class="control-group">
                <%= f.label :name, class: 'control-label' %>
                <div class="controls">
                    <%= f.text_field :name %>
                </div>
            </div>
            <div class+"control-group">
                <%= f.label :description, class: 'control-label' %>
                <div class="controls">
                    <%= f.text_area :description %>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <%= f.label :public, class: 'checkbox' do %>
                        <%= f.check_box :public %> Public topic
                    <% end %>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <%= f.submit "Save", class: 'btn' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/topics/show.html.erb
<% if policy(Topic.new).show? %>
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
    <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-primary btn-mini' %>
<% end %>

<div class="row">
    <div class="span8">
        <p class="lead"><%= @topic.description %></p>
        <% @posts.each do |post| %>
            <div class="media">
                <%= render partial: 'votes/voter', locals: { topic: @topic, post: post } %>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="<%= topic_post_path(@topic, post) %>">
                            <%= image_tag (post.post_image.thumb.url) if post.post_image? %>
                            <%= markdown post.title %>
                        </a>
                    </h4>
                    <small>
                        <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
                        submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
                        <%= post.comments.count %> Comments
                    </small>
                </div>
            </div>
        <% end %>
        <%= will_paginate @posts %>
    </div>

    <div class="span4">
        <% if policy(Post.new).create? %>
            <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-large btn-block' %>
        <% end %>

        <% if policy(Topic).destroy? %>
            <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this topic?' %>
        <% end %>
    </div>
</div>
<% end %>